### ISSUE TITLE
is this for a discord bot and will it work ?????

### ISSUE THREAD

**Issue by Reubencfernandes** [RealAlpha/discord-c#1]
i dont see a basic command for the bot

**Comment by midischwarz12** [comment]
@gco360 It is a library for the API in the C language as it says [here](https://github.com/RealAlpha/discord-c/blob/master/README.md?plain=1#L2). You can build against it by writing your own application. An example is provided at `./test` after compiling as stated [here](https://github.com/RealAlpha/discord-c/blob/master/README.md?plain=1#L14).
