### ISSUE TITLE
Token location

### ISSUE THREAD

**Issue by midischwarz12** [RealAlpha/discord-c#4]
There is no token location explicitly put into comment or as a namespace of any form. There should be a variable for such a parameter which is meant to be changed before compilation.

**Comment by lthoma5** [comment]
Thank you for raising this issue! Just to check, you're referring to the example (in main.c) right? If so, would creating a define (or the like) at the start of the file where users can place their tokens address this, or are you referring to something else?

**Comment by midischwarz12** [comment]
Yeah, a define in `main.c` would be great.

**Comment by lthoma5** [comment]
Resolved in a175eae

**Comment by midischwarz12** [comment]
Beautiful
